'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CustomizeTemplate.Web


    Partial Public Class DefaultVerticalTemplateContentNew

        ''' <summary>
        ''' UPPopupWindowControl control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPPopupWindowControl As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' PopupWindowControl control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected PopupWindowControl As Global.DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl

        ''' <summary>
        ''' UPSAC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPSAC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' SAC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

        ''' <summary>
        ''' navigation control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected navigation As Global.System.Web.UI.WebControls.Panel

        ''' <summary>
        ''' UPNC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPNC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' NC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer

        ''' <summary>
        ''' UPVIC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPVIC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' VIC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected VIC As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

        ''' <summary>
        ''' UPVH control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPVH As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' VCC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected VCC As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

        ''' <summary>
        ''' XafUpdatePanel1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected XafUpdatePanel1 As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' mainMenu control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected mainMenu As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

        ''' <summary>
        ''' XafUpdatePanel2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected XafUpdatePanel2 As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' SearchAC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SearchAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

        ''' <summary>
        ''' UPEI control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPEI As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' ErrorInfo control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

        ''' <summary>
        ''' UPVSC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected UPVSC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

        ''' <summary>
        ''' VSC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected VSC As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

        ''' <summary>
        ''' AIC control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AIC As Global.DevExpress.ExpressApp.Web.Controls.AboutInfoControl
    End Class
End Namespace
